# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (3)
# #########################################################################

class Education(BaseModel):
    institution: str
    degree: typing.Optional[str] = None
    field_of_study: typing.Optional[str] = None
    start_date: typing.Optional[str] = Field(default=None, description='ISO date YYYY-MM-DD or YYYY-MM format')
    end_date: typing.Optional[str] = Field(default=None, description='ISO date YYYY-MM-DD or YYYY-MM format')

class ParsedResume(BaseModel):
    applicant_name: str = Field(description='Full name of the candidate')
    email_id: typing.Optional[str] = Field(default=None, description='Primary email address')
    phone: typing.Optional[str] = Field(default=None, description='Primary phone number')
    current_company: typing.Optional[str] = Field(default=None, description='Most recent employer')
    designation: typing.Optional[str] = Field(default=None, description='Most recent job title')
    skills: typing.List[str] = Field(description='List of technical and soft skills')
    experience: typing.List["WorkExperience"] = Field(description='Work history, most recent first')
    education: typing.List["Education"] = Field(description='Education history, most recent first')
    linkedin_url: typing.Optional[str] = Field(default=None, description='LinkedIn profile URL if found')
    github_url: typing.Optional[str] = Field(default=None, description='GitHub profile URL if found')
    summary: typing.Optional[str] = Field(default=None, description='Brief professional summary, 1-2 sentences')

class WorkExperience(BaseModel):
    company: str
    title: str
    start_date: typing.Optional[str] = Field(default=None, description='ISO date YYYY-MM-DD or YYYY-MM format')
    end_date: typing.Optional[str] = Field(default=None, description='ISO date YYYY-MM-DD or YYYY-MM format, null if current')
    is_current: bool
    responsibilities: typing.Optional[str] = Field(default=None, description='Key responsibilities, comma-separated')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
