# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class Education(BaseModel):
    institution: typing.Optional[str] = None
    degree: typing.Optional[str] = None
    field_of_study: typing.Optional[str] = None
    start_date: typing.Optional[str] = Field(default=None, description='ISO date YYYY-MM-DD or YYYY-MM format')
    end_date: typing.Optional[str] = Field(default=None, description='ISO date YYYY-MM-DD or YYYY-MM format')

class ParsedResume(BaseModel):
    applicant_name: typing.Optional[str] = Field(default=None, description='Full name of the candidate')
    email_id: typing.Optional[str] = Field(default=None, description='Primary email address')
    phone: typing.Optional[str] = Field(default=None, description='Primary phone number')
    current_company: typing.Optional[str] = Field(default=None, description='Most recent employer')
    designation: typing.Optional[str] = Field(default=None, description='Most recent job title')
    skills: typing.List[str] = Field(description='List of technical and soft skills')
    experience: typing.List["WorkExperience"] = Field(description='Work history, most recent first')
    education: typing.List["Education"] = Field(description='Education history, most recent first')
    linkedin_url: typing.Optional[str] = Field(default=None, description='LinkedIn profile URL if found')
    github_url: typing.Optional[str] = Field(default=None, description='GitHub profile URL if found')
    summary: typing.Optional[str] = Field(default=None, description='Brief professional summary, 1-2 sentences')

class WorkExperience(BaseModel):
    company: typing.Optional[str] = None
    title: typing.Optional[str] = None
    start_date: typing.Optional[str] = Field(default=None, description='ISO date YYYY-MM-DD or YYYY-MM format')
    end_date: typing.Optional[str] = Field(default=None, description='ISO date YYYY-MM-DD or YYYY-MM format, null if current')
    is_current: typing.Optional[bool] = None
    responsibilities: typing.Optional[str] = Field(default=None, description='Key responsibilities, comma-separated')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
