# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Education": types.Education,
    "stream_types.Education": stream_types.Education,

    "types.ParsedResume": types.ParsedResume,
    "stream_types.ParsedResume": stream_types.ParsedResume,

    "types.WorkExperience": types.WorkExperience,
    "stream_types.WorkExperience": stream_types.WorkExperience,


}